[project]
name = "parrot"
version = "0.1.0"
description = "Parrot model: Takes audio as input and parrot's same audio in its own voice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "edge-tts>=7.2.7",
    "moshi>=0.2.12",
    "numpy>=2.2.6",
    "soundfile>=0.13.1",
    "speechbrain>=1.0.3",
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
    "transformers>=4.57.6",
    "wandb>=0.24.1",
]
