[project]
name = "parrot"
version = "0.1.0"
description = "Parrot model: Takes audio as input and parrot's same audio in its own voice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edge-tts>=7.2.7",
    "numpy>=2.4.2",
    "torchaudio>=2.10.0",
    "torchcodec>=0.1.0",
]
